### ISSUE TITLE
Demo minor issue - Hello message on Goodbye proc

### ISSUE THREAD

**Issue by darianmiller** [VSoftTechnologies/VSoft.Messaging#1]
Using a Hello message on a Goodbye proc

https://github.com/VSoftTechnologies/VSoft.Messaging/blob/master/demos/Vcl/MsgFrame.pas

procedure TMsgRecieverFrame.GoodBye(var msg: THelloMessage);

**Comment by vincentparrett** [comment]
Thanks, fixed.
